/obj/machinery/power/supermatter/Process()
	..()
	if(world.time) //> 10 MINUTES)
		for(var/area/A in world)
			if(A.z == loc.z)
				if(is_not_space_area(A))
					for(var/datum/gas_mixture/GM in A)
						if(GM.temperature > 20)
							GM.temperature += (-1 + (power/1000))